#!/bin/bash
# Download all 100 illustration website preview images

BASE_DIR="/home/chujiu/softwares/website/mywebsite/blog/source/img/posts-images/top-100-free-vector-illustration-websites"
cd "$BASE_DIR"

# Cover images
curl -sL -o "cover-hero.jpg" "https://getillustrations.com/blog/content/images/size/w2000/2025/10/Hipster-bible-to-illustrations.png"

# Free Illustrations (1-39)
curl -sL -o "001-undraw.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_001_undraw.co.png"
curl -sL -o "002-manypixels.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_002_manypixels.co.png"
curl -sL -o "003-skribbl.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_003_weareskribbl.com.png"
curl -sL -o "005-sketchvalley.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_005_sketchvalley.com.png"
curl -sL -o "006-lummi.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_006_lummi.ai.png"
curl -sL -o "007-illustrationkit.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_007_illustrationkit.com.png"
curl -sL -o "008-charco.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_008_charcodesign.gumroad.com.png"
curl -sL -o "009-blackillustrations.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_009_blackillustrations.com.png"
curl -sL -o "010-illlustrations.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_010_illlustrations.co.png"
curl -sL -o "011-pixeltrue.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_011_pixeltrue.com.png"
curl -sL -o "012-onfire.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_012_onfire.craftwork.design.png"
curl -sL -o "013-delesign.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_013_free-designs.delesign.com.png"
curl -sL -o "014-absurd.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_014_absurd.design.png"
curl -sL -o "015-freesvg.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_015_freeillustrations.xyz.png"
curl -sL -o "016-lukaszadam.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_016_lukaszadam.com.png"
curl -sL -o "017-reshot.jpg" "https://getillustrations.com/blog/content/images/2025/10/RESHOT-VECTOR-ILLUSTRATIONS.png"
curl -sL -o "019-doodleipsum.jpg" "https://getillustrations.com/blog/content/images/2025/10/Doodle-Ipsum-illustrations.png"
curl -sL -o "020-grads.jpg" "https://getillustrations.com/blog/content/images/2025/10/Gradients-illustrations.png"
curl -sL -o "021-humanities.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_021_levinunnink.gumroad.com.png"
curl -sL -o "022-svgdoodles.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_022_svgrepo.com.png"
curl -sL -o "023-openstickers.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_023_openstickers.craftwork.design.png"
curl -sL -o "024-scribbbles.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_024_scribbbles.design.png"
curl -sL -o "025-highlights.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_025_highlights.design.png"
curl -sL -o "026-storyset.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_026_storyset.com.png"
curl -sL -o "027-humaaans.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_027_humaaans.com.png"
curl -sL -o "029-avataaars.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_029_getavataaars.com.png"
curl -sL -o "030-opendoodles.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_030_opendoodles.com.png"
curl -sL -o "031-userpics.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_031_userpics.craftwork.design.png"
curl -sL -o "032-bigheads.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_032_bigheads.io.png"
curl -sL -o "034-openpeeps.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_034_openpeeps.com.png"
curl -sL -o "035-freshfolk.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_035_fresh-folk.com.png"
curl -sL -o "036-avataru.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_036_avatar-u.webflow.io.png"
curl -sL -o "037-avamaker.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_037_avamake.com.png"
curl -sL -o "038-notion.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_038_drawkit.com.png"
curl -sL -o "039-playful.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_040_drawkit.com-1.png"

# Freemium (40-50)
curl -sL -o "040-getillustrations.jpg" "https://getillustrations.com/blog/content/images/2025/10/Free-Website-illustrations-by-Getillustrations.png"
curl -sL -o "041-icons8.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_042_icons8.com.png"
curl -sL -o "042-blush.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_043_blush.design.png"
curl -sL -o "043-drawkit.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_044_drawkit.com.png"
curl -sL -o "044-freepik.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_045_freepik.com.png"
curl -sL -o "045-vecteezy.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_046_vecteezy.com.png"
curl -sL -o "046-absurd-premium.jpg" "https://getillustrations.com/blog/content/images/2025/10/Absurd-design-abstract-illustrations.png"
curl -sL -o "047-smash.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_048_usesmash.craftwork.design.png"
curl -sL -o "048-control.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_049_craftwork.design.png"
curl -sL -o "049-streamline.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_050_streamlinehq.com.png"
curl -sL -o "050-storytale.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_051_storytale.io.png"

# Premium (51-54)
curl -sL -o "051-storytale-premium.jpg" "https://getillustrations.com/blog/content/images/2025/10/Story-tale-illustrations.png"
curl -sL -o "052-getillustrations-premium.jpg" "https://getillustrations.com/blog/content/images/2025/10/Getillustrations-Figma-Plugin-Cover.png"
curl -sL -o "053-adobestock.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_053_stock.adobe.com.png"
curl -sL -o "054-shutterstock.jpg" "https://getillustrations.com/blog/content/images/2025/10/Shutter-stock-vector-illustrations.png"
curl -sL -o "055-manypixels-unlimited.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_055_manypixels.co-1.png"

# AI Generators (56-61)
curl -sL -o "056-leonardo.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_056_leonardo.ai.png"
curl -sL -o "057-recraft.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_057_recraft.ai.png"
curl -sL -o "058-firefly.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_058_firefly.adobe.com.png"
curl -sL -o "059-canva.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_059_canva.com.png"
curl -sL -o "060-illustroke.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_060_illustroke.com.png"
curl -sL -o "061-svgmaker.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_061_svgmaker.io.png"
curl -sL -o "062-recraft-vectorize.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_062_recraft.ai.png"

# 3D & Isometric (63-69)
curl -sL -o "063-3dicons.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_063_3dicons.co.png"
curl -sL -o "064-handz.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_064_handz.design.png"
curl -sL -o "065-illustrationz.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_065_illustrationz.design.png"
curl -sL -o "066-icograms.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_066_icograms.com.png"
curl -sL -o "067-isometricmaps.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_067_isometricmaps.com.png"
curl -sL -o "068-spline.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_068_spline.design.png"
curl -sL -o "069-shapefest.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_069_shapefest.com.png"

# Animated & Lottie (70-73)
curl -sL -o "070-lottiefiles.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_070_lottiefiles.com.png"
curl -sL -o "071-lordicon.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_071_lordicon.com.png"
curl -sL -o "072-rive.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_072_rive.app.png"
curl -sL -o "073-svgator.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_073_svgator.com.png"

# Mega-Libraries (74-78)
curl -sL -o "074-canva.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_074_canva.com.png"
curl -sL -o "075-nounproject.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_075_thenounproject.com.png"
curl -sL -o "076-flaticon.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_076_flaticon.com.png"
curl -sL -o "077-pixabay.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_077_pixabay.com.png"
curl -sL -o "078-vectoricons.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_078_vectoricons.net.png"

# Niche (79-100)
curl -sL -o "079-publicdomainvectors.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_080_publicdomainvectors.org.png"
curl -sL -o "080-clipsafari.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_081_clipsafari.com.png"
curl -sL -o "081-haikei.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_082_app.haikei.app.png"
curl -sL -o "082-svgbackgrounds.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_083_svgbackgrounds.com.png"
curl -sL -o "083-heropatterns.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_084_heropatterns.com.png"
curl -sL -o "084-heroicons.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_085_heroicons.com.png"
curl -sL -o "085-ira.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_086_iradesign.io.png"
curl -sL -o "086-svgrepo.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_087_svgrepo.com.png"
curl -sL -o "087-visme.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_088_visme.co.png"
curl -sL -o "088-uiillustrations.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_089_uiillustrations.com.png"
curl -sL -o "089-designstripe.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_090_designstripe.com.png"
curl -sL -o "090-pixelbuddha.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_091_pixelbuddha.net.png"
curl -sL -o "091-designsai.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_092_designs.ai.png"
curl -sL -o "092-stockio.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_093_stockio.com.png"
curl -sL -o "093-vector4free.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_094_vector4free.com.png"
curl -sL -o "094-vectorstock.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_095_vectorstock.com.png"
curl -sL -o "095-vexels.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_096_vexels.com.png"
curl -sL -o "096-iconsax.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_097_iconsax.io.png"
curl -sL -o "097-humanistavatars.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_098_humanistavatars.com.png"
curl -sL -o "098-uxwing.jpg" "https://getillustrations.com/blog/content/images/2025/10/illustration-website_099_uxwing.com.png"
curl -sL -o "099-lovepik.jpg" "https://getillustrations.com/blog/content/images/2025/10/Screenshot-2025-10-29-at-11.06.25---AM.png"
curl -sL -o "100-roundicons.jpg" "https://getillustrations.com/blog/content/images/2025/10/Roundicons-Vector-icons-website-lirbary.png"

echo "Download complete!"
ls -1 *.jpg | wc -l
echo "images downloaded"
